### ISSUE TITLE
failed to load source for dependency `pixels`

### ISSUE THREAD

**Issue by maehw** [nickik/ledsim#1]
Hi, sorry I am a noob in the dependency management and don't have a clue how `cargo` works.

Could you please give me a hint how to fix the missing dependency?

```
$ cargo run --release --package ledsim -- 54321 24 48
    Updating crates.io index
error: failed to get `pixels` as a dependency of package `ledsim v0.1.0 (/home/maehw/local_repos/ledsim)`

Caused by:
  failed to load source for dependency `pixels`

Caused by:
  Unable to update /home/maehw/local_repos/pixels

Caused by:
  failed to read `/home/maehw/local_repos/pixels/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

I tried `cargo install pixels` and `cargo add pixels`. I am quite sure that this is easily fixable if you know how to do it.

Cheers

**Comment by maehw** [comment]
Can be closed. Just had to pull... fixed itself. :) Thanks for the help!

**Comment by nickik** [comment]
Fixed in newer version.
